#!/bin/sh -f 
clear
echo '***************start****************!'
beginTime=`date +%s`


     #lon=10
     #lat=85
for lon in $(seq 1 2 3)
do
    for lat in $(seq 70 2 72)
    do
    {
     

    echo "--------------  lon= $lon, lat= $lat  -------------- "

 
    #preparing modis observation
    echo 'modifling matlab script ...'
    sed -i "193c lon_goal = $lon;    lat_goal = $lat ;" ./MODIS_squeeze_operational.m
    sed -i "9c year = 2005; lon = $lon; lat = $lat ;" ./MODIS_8d_ip_1h_operational.m

#    dos2unix ./MODIS_squeeze_operational.m
#    dos2unix ./MODIS_8d_ip_1h_operational.m

    echo 'running matlab ...'
    nohup matlab -nojvm -nodisplay -nosplash -logfile log.matlab <MODIS_squeeze_operational.m
    nohup matlab -nojvm -nodisplay -nosplash -logfile log.matlab <MODIS_8d_ip_1h_operational.m


    modis_8d_file="modis_2005_"$lon"_"$lat"_08day.txt"
    modis_file="modis_2005_"$lon"_"$lat"_01hour_ip.txt"
#    echo "modis_file= $modis_file"

     

    # preparing jra atm forcing
    jra_file="jra55_2005_"$lon"_"$lat"_01hr.txt"
    
    if [ -e "/home/luy/Icepack_data/forcing/CFS/$jra_file"  ] ; then
       echo "exist"
       # run producing intermediate pond forcing
       cd /home/luy/icepack/producing_intermediate_forcing/run_jra
       # change the so-called 'in file'
       sed -i "96c            atm_data_file   = '$jra_file' " ./icepack_in
       ./automatic_formalrun
    
       # run parameter estimation
       # change fortran code
       cd /home/luy/icepack/cesm_meltpond_pe/run_real
    
       echo 'modifling fortran code ...'
       sed -i "225c       print *, 'Reading ','$modis_file' " ../build_real/driver/icedrv_MAIN.F90
       sed -i "227c       open (12, file='$modis_file')"      ../build_real/driver/icedrv_MAIN.F90

       dos2unix ../build_real/driver/icedrv_MAIN.F90
       # rebuild
       cd ../build_real ; ./build_driver2_fast.sh ; 
       # change run congfiguration
       cd ../run_real ; 
       sed -i "96c            atm_data_file   = '$jra_file' " ./icepack_in
       
       # run The parameter estimation MAIN program
       bash automatic_BuildRunQueryDataSend_partbypart ;

    else
       echo "not exist"
    fi


    # run fwd using new estimated parameter
    cp pndaspect.txt ~/icepack/run_jra
    cd ~/icepack/run_jra

    sed -i "3c lon=$lon; lat=$lat;" ./automatic_change_atm_forcing
    bash automatic_change_atm_forcing
    bash automatic_get_estimated_parameter
    bash automatic_run_whole
    bash automatic_run_partbypart

    # sz modis file
    #sz modis_2005_"$lon"_"$lat"_08day.txt
    #sz modis_2005_"$lon"_"$lat"_01hour_ip.txt

    # sz pndaspect file
#    sz pndaspect.txt
    mv pndaspect.txt pndaspect_"$lon"_"$lat".txt
#    sz pndaspect_"$lon"_"$lat".txt
    
    echo "-----------------------------------------------------------"

    }&
    done
done

wait

endTime=`date +%s`
echo "总共耗时:" $(($endTime-$beginTime)) "秒"
echo '*************finish***************'
