#!/bin/sh -f 
clear
echo '!_____________start_______________!'
echo "the_dir_is:____ $PWD"
echo "run started : `date`"




for lon in $(seq 150 150)
do
    for lat in $(seq 85 85)
    do

    echo "--------------  lon= $lon, lat= $lat  -------------- "
 
    #preparing modis observation
    echo 'modifling matlab script ...'
    sed -i "193c lon_goal = $lon;    lat_goal = $lat ;" ./MODIS_squeeze_operational.m

    dos2unix ./MODIS_squeeze_operational.m

    echo 'running matlab ...'
    nohup matlab -nojvm -nodisplay -nosplash -logfile log.matlab <MODIS_squeeze_operational.m


    modis_file="modis_2005_"$lon"_"$lat"_08day.txt"
    echo "modis_file= $modis_file"

    # preparing jra forcing
    jra_file="jra55_2005_"$lon"_"$lat"_01hr.txt"
    
    if [ -e "/home/luy/Icepack_data/forcing/CFS/$jra_file"  ] ; then
       echo "exist"
       # run producing intermediate forcing
       cd /home/luy/icepack/producing_intermediate_forcing/run_jra
       # change the so-called 'in file'
       sed -i "96c            atm_data_file   = '$jra_file' " ./icepack_in
       ./automatic_formalrun
    
       # run parameter estimation
       # change fortran code
       cd /home/luy/icepack/cesm_meltpond_pe/run_real
    
       echo 'modifling fortran code ...'
       sed -i "192c       print *, 'Reading ','$modis_file' " ../build_real/driver/icedrv_MAIN.F90
       sed -i "194c       open (12, file='$modis_file')"      ../build_real/driver/icedrv_MAIN.F90

       dos2unix ../build_real/driver/icedrv_MAIN.F90
       # rebuild
       cd ../build_real ; ./build_driver2.sh ; 
       # change run congfiguration
       cd ../run_real ; 
       sed -i "96c            atm_data_file   = '$jra_file' " ./icepack_in
       # run
       ./automatic_formalrun

       # save parameter estimation results to text file for future using
       # find the newest runlog file
#       ls ./icepack.runlog.* | sort > icepack.runloglist.txt
#       latest_logfile=`tail -n 1 icepack.runloglist.txt`
#       echo $latest_logfile

       # extract useful data from the runlog file
#       iflag=$(grep "IFLAG" $latest_logfile | cut -f 2 -d"=" | sed 's/ //g')
       #echo $iflag
#       if [[ $iflag -eq 0 ]]
#       then
 #        echo 'iflag=0' 
  #     else
   #      echo 'iflag=-1'
    #   fi

    else
       echo "not exist"
    fi

    done
done
echo "run finished : `date`"
echo '!_____________finish_______________!'
