#!/bin/csh -f 

echo '!'
echo 'pwd: the current dir is :'

pwd

echo '!'

echo 'cp ../build/icepack .'
cp -a ../build/icepack .

echo '!'

echo './icepack.submit.debug'
./icepack.submit.debug

echo 'waiting ...'

echo '!'

