#!/bin/sh -f 
clear
echo '!_____________start_______________!'
echo "the_dir_is:____ $PWD"

rm -rf iflag.txt
rm -rf X.txt

for lon in $(seq 240 240)
do
    for lat in $(seq 70 70)
    do

    echo "^^^^^^^^^^^^^^ lon= $lon, lat= $lat  ^^^^^^^^^^^^^^^^^ "

    echo 'modifling matlab script ...'
    sed -i "193c lon_goal = $lon;    lat_goal = $lat ;" ./MODIS_squeeze_operational.m

    dos2unix ./MODIS_squeeze_operational.m

    echo 'running matlab ...'
    nohup matlab -nojvm -nodisplay -nosplash -logfile log.matlab <MODIS_squeeze_operational.m


    modis_file="modis_2005_"$lon"_"$lat"_08day.txt"
    echo "modis_file= $modis_file"

    echo 'modifling fortran script ...'
    sed -i "185c       print *, 'Reading ','$modis_file' " ../build_real/driver/icedrv_MAIN.F90
    sed -i "187c       open (12, file='$modis_file')"      ../build_real/driver/icedrv_MAIN.F90

    dos2unix ../build_real/driver/icedrv_MAIN.F90

    cd ../build_real ; ./build_driver2.sh ; cd ../run_real ; ./automatic_formalrun

    ls ./icepack.runlog.* | sort > icepack.runloglist.txt
    latest_logfile=`tail -n 1 icepack.runloglist.txt`
    echo $latest_logfile

    iflag=$(grep "IFLAG" $latest_logfile | cut -f 2 -d"=" | sed 's/ //g')
    #echo $iflag
    if [[ $iflag -eq 0 ]]
    then
      echo 'iflag=0' 
      echo 1 >> iflag.txt
      sed -n " `grep -n "FINAL POINT X=" $latest_logfile | awk -F ":" '{print $1}'`,+1p " $latest_logfile | tail -n 1 >> X.txt 
    else
      echo 'iflag=-1'
      echo -1 >> iflag.txt
      echo nan >> X.txt
    fi



    done
done

echo '!_____________finish_______________!'
