#!/bin/csh -f 

yhq
#cat slurm-1724989.out
#vi icepack.runlog.190628-160414
#tail -n 5 icepack.runlog.190628-160414
vi ice_diag.full_ITD
#/THL6/home/xcwang/luy/CICE/CICE-master/icepack/configuration/scripts/tests/timeseries.csh ./ice_diag.full_ITD
./timeseries.csh ./ice_diag.full_ITD
