#!/bin/sh -f 
clear
echo '-----------------------------------------------------------'
beginTime=`date +%s`
echo "run started : `date "+%Y-%m-%d %H:%M:%S"` "



lon_list=(210 240 180 240 300 350 190 170 220 90 60)
lat_list=(80  80  85  85  85  85  70  73  80  78 78)
#for lon in $(seq 1 2 360)
#do
#    for lat in $(seq 70 2 88)
#    do
for j in $(seq 9 9)
do
{
    lon=${lon_list[$j]}
    lat=${lat_list[$j]}

    echo "------------------  lon= $lon, lat= $lat  ------------------- "
    # initial condition of FYI and MYI
    if [ $[j] -gt 5 ]; then
      sed -i "1175c  hbar = 2.0_dbl_kind  ! Lu Yang " ../build_real/driver/icedrv_init.F90 # FYI
    else 
      sed -i "1175c  hbar = 3.68000_dbl_kind  ! Lu Yang " ../build_real/driver/icedrv_init.F90 # MYI
    fi 

 
    #preparing modis observation
    echo 'modifling matlab script ...'
    sed -i "193c lon_goal = $lon;    lat_goal = $lat ;" ./MODIS_squeeze_operational.m
    sed -i "9c year = 2005; lon = $lon; lat = $lat ;" ./MODIS_8d_ip_1h_operational.m

#    dos2unix ./MODIS_squeeze_operational.m
#    dos2unix ./MODIS_8d_ip_1h_operational.m

    echo 'running matlab ...'
    nohup matlab -nojvm -nodisplay -nosplash -logfile log.matlab <MODIS_squeeze_operational.m
    nohup matlab -nojvm -nodisplay -nosplash -logfile log.matlab <MODIS_8d_ip_1h_operational.m


    modis_8d_file="modis_2005_"$lon"_"$lat"_08day.txt"
    modis_file="modis_2005_"$lon"_"$lat"_01hour_ip.txt"
    echo "modis_file= $modis_file"

     

    # preparing jra atm forcing
    jra_file="jra55_2005_"$lon"_"$lat"_01hr.txt"
    
    if [ -e "/home/luyang/Icepack_data/forcing/CFS/$jra_file"  ] ; then
       echo "exist"
       # run producing intermediate pond forcing
       cd /home/luyang/icepack/producing_intermediate_forcing/run_jra
       # change the so-called 'in file'
       sed -i "96c            atm_data_file   = '$jra_file' " ./icepack_in
       ./automatic_formalrun
    
       # run parameter estimation
       # change fortran code
       cd /home/luyang/icepack/cesm_meltpond_pe/run_real
    
       echo 'modifling fortran code ...'
       sed -i "225c       print *, 'Reading ','$modis_file' " ~/icepack/cesm_meltpond_pe/build_real/driver/icedrv_MAIN.F90
       sed -i "227c       open (12, file='$modis_file')"      ~/icepack/cesm_meltpond_pe/build_real/driver/icedrv_MAIN.F90

       dos2unix ../build_real/driver/icedrv_MAIN.F90
       # rebuild icepack
       cd ../build_real ; ./build_driver2_fast.sh ; 
       # change run congfiguration
       cd ../run_real ; 
       sed -i "96c            atm_data_file   = '$jra_file' " ./icepack_in
       
       # run The parameter estimation MAIN program
       bash automatic_BuildRunQueryDataSend_partbypart ;

    else
       echo "not exist"
    fi


# run fwd using new estimated parameter
    cp pndaspect.txt ~/icepack/run_jra
    cd ~/icepack/run_jra

    # change atmospheric forcing of FYI and MYI
    sed -i "3c lon=$lon; lat=$lat;" ./automatic_change_atm_forcing

    # initial condition of FYI and MYI
    if [ $[j] -gt 5 ]; then
      sed -i "1175c  hbar = 2.0_dbl_kind  ! Lu Yang ,FYI" ~/icepack/build_pond/driver/icedrv_init.F90
    else 
      sed -i "1175c  hbar = 3.68000_dbl_kind  ! Lu Yang, MYI" ~/icepack/build_pond/driver/icedrv_init.F90
    fi 
    
    # rebuild icepack
    cd ~/icepack/build_pond
    bash build_driver2_fast.sh

    cd ~/icepack/run_jra
    bash automatic_change_atm_forcing
    bash automatic_get_estimated_parameter
    bash automatic_run_whole  # run 1a using default parameter, 0.8
    bash automatic_run_partbypart # run part by part, using estimated parameter

## sz modis file
#    sz modis_2005_"$lon"_"$lat"_08day.txt
#    sz modis_2005_"$lon"_"$lat"_01hour_ip.txt

# sz pndaspect file
    sz pndaspect.txt
    mv pndaspect.txt pndaspect_"$lon"_"$lat".txt
    sz pndaspect_"$lon"_"$lat".txt
} 
    #done
done

echo "run finished : `date`"
endTime=`date +%s`
echo "总共耗时:" $(($endTime-$beginTime)) "秒"
echo '-----------------------------------------------------------'
